//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.12 at 05:49:35 PM PYT 
//


package ws.tigomoney.tigo.com;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;

@XmlAccessorType(XmlAccessType.FIELD)
//@XmlType(name = "existsCI", propOrder = {
//    "consumerID",
//    "consumerPWD",
//    "transactionID",
//    "source",
//    "ci"
//})
public class ExistsCI extends BaseRequest{

    @XmlElement(required = true)
    protected String ci;

    public String getCi() {
        return ci;
    }

    public void setCi(String value) {
        this.ci = value;
    }

	@Override
	public String toString() {
		return "[consumerID=" + consumerID + ", consumerPWD="
				+ consumerPWD + ", transactionID=" + transactionID
				+ ", source=" + source + ", ci=" + ci + "]";
	}
    
    
    

}
