//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.19 at 06:01:21 PM PYT 
//


package ws.tigomoney.tigo.com;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.datatype.XMLGregorianCalendar;

@XmlAccessorType(XmlAccessType.FIELD)
//@XmlType(name = "updateCI", propOrder = {
//    "consumerID",
//    "consumerPWD",
//    "transactionID",
//    "ci",
//    "birthDate",
//    "address",
//    "city",
//    "frontPhoto",
//    "backPhoto",
//    "source"
//})
public class UpdateCI extends BaseRequest{
    
    @XmlElement(required = true)
    protected String ci;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar birthDate;
    @XmlElement(required = true)
    protected String address;
    @XmlElement(required = true)
    protected String city;
    @XmlElementRef(name = "frontPhoto", type = JAXBElement.class)
    protected JAXBElement<byte[]> frontPhoto;
    @XmlElementRef(name = "backPhoto", type = JAXBElement.class)
    protected JAXBElement<byte[]> backPhoto;
    
    public String getCi() {
        return ci;
    }

    public void setCi(String value) {
        this.ci = value;
    }
    
    public XMLGregorianCalendar getBirthDate() {
        return birthDate;
    }

    public void setBirthDate(XMLGregorianCalendar value) {
        this.birthDate = value;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String value) {
        this.address = value;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String value) {
        this.city = value;
    }

    public JAXBElement<byte[]> getFrontPhoto() {
        return frontPhoto;
    }

    public void setFrontPhoto(JAXBElement<byte[]> value) {
        this.frontPhoto = ((JAXBElement<byte[]> ) value);
    }

    public JAXBElement<byte[]> getBackPhoto() {
        return backPhoto;
    }

    public void setBackPhoto(JAXBElement<byte[]> value) {
        this.backPhoto = ((JAXBElement<byte[]> ) value);
    }

	@Override
	public String toString() {
		return "[consumerID=" + consumerID + ", consumerPWD="
				+ consumerPWD + ", transactionID=" + transactionID + ", ci="
				+ ci + ", birthDate=" + birthDate + ", address=" + address
				+ ", city=" + city + ", frontPhoto=" + frontPhoto
				+ ", backPhoto=" + backPhoto + ", source=" + source + "]";
	}

    
}
