package com.tigo.cs.api.util;

public enum JMSProperties {
    JMSQUEUENAME,
    JMSQUEUECONNFACTORY,
    INITIALCONTEXTFACTORY,
    JMSSERVER,
    URLPKGPREFIXES,
    DESTINO,
    IDPLATAFORMA,
    PROCESO,
    MENSAJE

}
